# Generated by Django 3.2.6 on 2021-09-05 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_extendeduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='ImageList',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.imagelist'),
        ),
        migrations.AlterField(
            model_name='note',
            name='List',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.list'),
        ),
    ]
