# Generated by Django 3.2.6 on 2021-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_imagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Labels',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='Reminder',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
