# Generated by Django 3.2.6 on 2021-08-20 09:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_extendeduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Title',
            field=models.CharField(default='Task-list', max_length=30),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='Profile',
            field=models.ImageField(default='notes/default.jpg', upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(default='notes/default.jpg', upload_to=api.models.user_directory_path2),
        ),
    ]
