# Generated by Django 3.2.6 on 2021-08-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210820_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Alt',
        ),
        migrations.RemoveField(
            model_name='image',
            name='Name',
        ),
    ]
