# Generated by Django 3.2.6 on 2021-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210820_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Background_color',
            field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('black', 'Black')], default='white', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='Images',
            field=models.ManyToManyField(default=None, related_name='Notes', to='api.Image'),
        ),
    ]
