# Generated by Django 3.2.6 on 2021-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210820_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Reminder',
            field=models.DateTimeField(default=None),
        ),
    ]
